version: '3'

services:
  db:
    image: mysql:${MYSQL_VERSION}
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  wordpress:
    depends_on:
      - db
    build:
      context: ./php
      dockerfile: "./Dockerfile-${PHP_VERSION}"
    ports:
      - "${PHP_PORT}:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${PHP_APPLICATION_DIR}:/var/www/html

volumes:
    db_data:
